name: Inspections

on:
  pull_request:

jobs:
  inspections:
    name: Inspections
    runs-on: ubuntu-latest
    strategy:
      matrix:
        inspection_command: ["lint", "types:validate", "test:ci"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.2'
          check-latest: true
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run inspection
        run: npm run ${{ matrix.inspection_command }}
